### ISSUE TITLE
Please update to new Swift

### ISSUE THREAD

**Issue by bramboe** [acaia/acaia_sdk_ios#1]
Please update to Swift 5 also:

`acaia_sdk_ios-master/Example-swift/AcaiaSDKExampleSwift.xcodeproj The file “Pods-AcaiaSDKExampleSwift.debug.xcconfig” couldn’t be opened because there is no such file. (acaia_sdk_ios-master/Example-swift/Pods/Target Support Files/Pods-AcaiaSDKExampleSwift/Pods-AcaiaSDKExampleSwift.debug.xcconfig)`

**Comment by TabMorty** [comment]
Example app  updated to Swift5 and Xcode 10.3
Please use pod
