### ISSUE TITLE
The package is non functional in Xcode 13.3

### ISSUE THREAD

**Issue by SwiftyAlex** [acaia/acaia_sdk_ios#12]
Due to a change in Xcode 13.3 requiring binary target names to match their framework names exactly, the framework will not compile.

The issue can be seen inside the `Package.swift` file. Every reference to `acaia_sdk_ios` needs to be changed to `AcaiaSDK`.

https://github.com/acaia/acaia_sdk_ios/blob/8bccc9bfe70e8fde3362554ff52c3a7c7d9aac40/Package.swift#L9
https://github.com/acaia/acaia_sdk_ios/blob/8bccc9bfe70e8fde3362554ff52c3a7c7d9aac40/Package.swift#L13
https://github.com/acaia/acaia_sdk_ios/blob/8bccc9bfe70e8fde3362554ff52c3a7c7d9aac40/Package.swift#L14
https://github.com/acaia/acaia_sdk_ios/blob/8bccc9bfe70e8fde3362554ff52c3a7c7d9aac40/Package.swift#L20

I have opened a [PR](https://github.com/acaia/acaia_sdk_ios/pull/11) to fix this already.

**Comment by TabMorty** [comment]
Please check latest 1.5.1 release
