### ISSUE TITLE
Support for pearl model s

### ISSUE THREAD

**Issue by luxus** [acaia/acaia_sdk_ios#3]
Apps like Filtru wanna add support for the pearl model s. But there is no support by the api so far 

https://twitter.com/AcaiaCoffee/status/1164996241530478592

**Comment by bobek-balinek** [comment]
@acaiadeveloperteam @MizukiHo any update on this? Is the support for Pearl S still in the works?

**Comment by josserman** [comment]
Please provide support for this.

**Comment by TabMorty** [comment]
Pearl S support is coming ....

**Comment by bobek-balinek** [comment]
@TabMorty thanks for letting us know! Do you have a time estimate of when it might arrive?
