### ISSUE TITLE
Support for Baratza Sette 270wi

### ISSUE THREAD

**Issue by martinh2011** [acaia/acaia_sdk_ios#4]
The current version of the Acaia Brewmaster app is able to read the weight from the Baratza Sette 270wi grinder. However, the SDK published via this repo currently does not support it. 

It would be great if the acaia ios sdk would be able to support the acaia scale built-in to the Baratza Sette 270wi grinder.

**Comment by TabMorty** [comment]
This is a feature you will have to request from Baratza.
