### ISSUE TITLE
Open-sourcing the source of the SDK

### ISSUE THREAD

**Issue by freak4pc** [acaia/acaia_sdk_ios#5]
Hey there,
There seems to be some current issues with the SDK that could be really improved by the community if you open-source the actual source code.

For example:
1. Extremely verbose logging - basically anything through `CBCentralManager` is printed out to the console
2. Misuse of APIs. Attempting to connect while in wrong state causes delay/hang in connection: `AcaiaSDKExampleSwift[498:32031] [CoreBluetooth] API MISUSE: <CBCentralManager: 0x2839c00e0> can only accept this command while in the powered on state`
3. Also, the SDK seems to only be built for iOS. If the code is open-sourced we can make it work for Linux so it can be used on Server-Side Swift, or for macOS. 

Given your apps are also really not maintained, etc, it's a shame. At least give us the power to make tools that could benefit us, with such an expensive piece of hardware.

Please consider opening up the source code, and let your developer community thrive :)

**Comment by TabMorty** [comment]
Thank you for your feedback. 

If open source is considered, it will be announced through our usual channels, including here in this Git repo.

**Comment by freak4pc** [comment]
Is there any chance you’ll consider at least building it for macOS as well?
