### ISSUE TITLE
Timer notification doesn't fire

### ISSUE THREAD

**Issue by freak4pc** [acaia/acaia_sdk_ios#8]
Hello, I noticed the timer notification `AcaiaScaleTimer` doesn't actually fire any updates / values (I'm using a Lunar).

I tried both the example app and my own implementation. `startTimer()` work correctly and starts the timer on the scale, but I'm not getting any updates back. 

Weight updates are coming back correctly, as expected.

Would appreciate your help :) 

Thanks!

**Comment by jasonneurohr** [comment]
Seems to just be some minor fixes in the code - I have submitted a PR with the fix - #9

**Comment by freak4pc** [comment]
Uhm yeah that sort of fixes it. Problem is it only works if you actively stop and start the timer, but if it seems that if:

a. It is already running while you're connecting to the scale; or
b. It auto-starts in the auto-timer mode

There are no notifications fired, so this is still a bug IMO

**Comment by freak4pc** [comment]
Was this actually fixed or just closed because it's too old @TabMorty ?

**Comment by TabMorty** [comment]
@freak4pc both actually. There are some timer logic being looked at now to resolve some of the start/stop issues. 
The repo will be updated when code is ready.

**Comment by tudoro** [comment]
Hi,

Is there any news about the timer problem being fixed. I don't see another ticket about that and I am wondering if this is still on the roadmap.

Best regards,
Tudor
